apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: tutum-storage
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: tutum
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin

