apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - alb-ingress.yaml
  - sonar-ingress.yaml
  - peer-authentication.yaml
  - private-nodepools.yaml
  - eks-builtin-nodepools.yaml

patches:
  - path: replicas-patch.yaml
  - path: resource-tuning-patch.yaml
  - path: remove-nodeselector-patch.yaml
  - path: workload-nodepool-patch.yaml
  - path: kafka-startup-probe-patch.yaml

images:
  - name: 903913341620.dkr.ecr.ap-northeast-2.amazonaws.com/tutum/frontend
    newTag: b3a9e339
  - name: 903913341620.dkr.ecr.ap-northeast-2.amazonaws.com/tutum/backend
    newTag: 74539d4a
  - name: 903913341620.dkr.ecr.ap-northeast-2.amazonaws.com/tutum/workers
    newTag: 932dbaf0
  - name: 903913341620.dkr.ecr.ap-northeast-2.amazonaws.com/tutum/auth
    newTag: 9f43b170
