apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: tutum-app
spec:
  template:
    spec:
      containers:
        - name: auth
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 768Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tutum-app
spec:
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 300m
              memory: 768Mi
            limits:
              cpu: 500m
              memory: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: tutum-data
spec:
  template:
    spec:
      containers:
        - name: kafka
          resources:
            requests:
              cpu: 300m
              memory: 1536Mi
            limits:
              cpu: 1
              memory: 2Gi
