apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: tutum-app
  labels:
    app: auth
    app.kubernetes.io/name: auth
    app.kubernetes.io/part-of: tutum
spec:
  selector:
    app: auth
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP
