apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tutum-app
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: tutum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 192.168.56.12:8080/tutum/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URL
              value: "mongodb://mongodb.tutum-data.svc.cluster.local:27017"
            - name: REDIS_URL
              value: "redis://redis.tutum-data.svc.cluster.local:6379"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.tutum-data.svc.cluster.local:9092"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
