apiVersion: v1
kind: Secret
metadata:
  name: news-pipeline-secret
  namespace: tutum-app
  labels:
    app.kubernetes.io/part-of: tutum
    app.kubernetes.io/name: news-pipeline
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb.tutum-data.svc.cluster.local:27017"
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""