apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-consumer
  namespace: tutum-app
  labels:
    app: news-consumer
    app.kubernetes.io/name: news-consumer
    app.kubernetes.io/part-of: tutum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-consumer
  template:
    metadata:
      labels:
        app: news-consumer
    spec:
      nodeSelector:
        workload: app
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: news-consumer
          image: 192.168.56.12:8080/tutum/node3-consumer:v1
          imagePullPolicy: IfNotPresent
          command: ["python", "-u", "consumer.py"]
          envFrom:
            - configMapRef:
                name: news-pipeline-config
            - secretRef:
                name: news-pipeline-secret
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi