apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-consumer
  namespace: tutum-app
  labels:
    app: price-consumer
    app.kubernetes.io/name: price-consumer
    app.kubernetes.io/part-of: tutum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-consumer
  template:
    metadata:
      labels:
        app: price-consumer
    spec:
      containers:
        - name: price-consumer
          image: 192.168.56.12:8080/tutum/workers:latest
          command: ["python", "-u", "price_consumer.py"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.tutum-data.svc.cluster.local:9092"
            - name: MONGODB_URL
              value: "mongodb://mongodb.tutum-data.svc.cluster.local:27017"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
