apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml

images:
  - name: 903913341620.dkr.ecr.ap-northeast-2.amazonaws.com/tutum/frontend
    newTag: placeholder
  - name: 903913341620.dkr.ecr.ap-northeast-2.amazonaws.com/tutum/backend
    newTag: placeholder
  - name: 903913341620.dkr.ecr.ap-northeast-2.amazonaws.com/tutum/workers
    newTag: placeholder
